- name: Clone git repository
  ansible.builtin.git:
    repo: "https://github.com/iphilka/stud-template.git"
    dest: "/home/ansible-worker/www/stud-template"
    update: no
    clone: yes
  tags: git_clone
